# Generated by Django 3.0.5 on 2020-07-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200724_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='../static/images/person.png', upload_to='profile/'),
        ),
    ]
