# Generated by Django 3.0.5 on 2020-04-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20200424_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='filtered_image',
        ),
    ]
