# Generated by Django 3.0.5 on 2020-06-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_auto_20200607_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
